version: '3.8'

services:

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    expose:
      - 3001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db-dor
      - PORT=3001
    depends_on:
      - db

  front-end:
    build: ./client
    restart: always
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-dor