version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:B4hJDugzkzwiwf7RF2tqS52W4LqQdWs6@dpg-cqg1ip1u0jms7389kue0-a.oregon-postgres.render.com/rede_dor
      - PORT=3001
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: B4hJDugzkzwiwf7RF2tqS52W4LqQdWs6
      POSTGRES_DB: rede_dor
